### ISSUE TITLE
Crash on upload image and go back

### ISSUE THREAD

**Issue by niteshkhilwani** [vijayrawatsan/android-json-form-wizard#12]
Hello,

Thanks for uploading this useful code. One issue is coming in current version:

Issue: Crash on uploading image and going forward and coming back.

How to reproduce: 
1: upload image in page 1
2: Go to page 2. 
3.  Write some text
4. Go back to page 1. 
(Crash). 

Can you please check.

**Comment by vijayrawatsan** [comment]
@nitesh35103 
Can you please share your input data.json? So that I can replicate.
Thanks

**Comment by niteshkhilwani** [comment]
@vijayrawatsan 
The same used in demo.

**Comment by vijayrawatsan** [comment]
I tested with the latest code. I am not able to reproduce.

**Comment by niteshkhilwani** [comment]
Hi,

The testing device is on Android 4.3 .

Manifest file is: 

repositories {
    maven {
        url "https://jitpack.io"
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'com.github.vijayrawatsan:android-json-form-wizard:1.0'

}

**Comment by niteshkhilwani** [comment]
@vijayrawatsan 

Out of memory error is coming while testing. May be we need to put some check while uploading heavy images?

07-28 16:54:36.773  20883-20883/com.example.nitesh.form E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.OutOfMemoryError
            at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:623)
            at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:378)
            at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:417)
            at com.vijay.jsonwizard.interactors.JsonFormInteractor.getViewsFromJson(JsonFormInteractor.java:165)
            at com.vijay.jsonwizard.interactors.JsonFormInteractor.fetchFormElements(JsonFormInteractor.java:56)
            at com.vijay.jsonwizard.presenters.JsonFormFragmentPresenter.addFormElements(JsonFormFragmentPresenter.java:49)
            at com.vijay.jsonwizard.fragments.JsonFormFragment.onViewCreated(JsonFormFragment.java:69)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.popFromBackStack(BackStackRecord.java:960)
            at android.support.v4.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1553)
            at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:506)
            at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:178)
            at com.vijay.jsonwizard.fragments.JsonFormFragment.backClick(JsonFormFragment.java:220)
            at com.vijay.jsonwizard.presenters.JsonFormFragmentPresenter.onBackClick(JsonFormFragmentPresenter.java:69)
            at com.vijay.jsonwizard.fragments.JsonFormFragment.onOptionsItemSelected(JsonFormFragment.java:94)
            at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:1897)
            at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2046)
            at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:359)
            at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:144)
            at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:99)
            at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:99)
            at android.support.v7.internal.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:190)
            at android.view.View.performClick(View.java:4475)
            at android.view.View$PerformClick.run(View.java:18786)
            at android.os.Handler.handleCallback(Handler.java:730)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:176)
            at android.app.ActivityThread.main(ActivityThread.java:5419)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by vijayrawatsan** [comment]
@nitesh35103 
I think you don't have the latest code with you. getViewsFromJson has moved out from JsonFormInteractor.
Please pull the latest code base and run your with your json. Print stacktrace with latest code.
Thanks

**Comment by niteshkhilwani** [comment]
@vijayrawatsan  Thanks,

Tried with lite image (45kb) worked smoothly. 

But with 2MB image, following error came:

java.lang.OutOfMemoryError
            at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:623)
            at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:378)
            at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:417)
            at com.vijay.jsonwizard.widgets.ImagePickerFactory.getViewsFromJson(ImagePickerFactory.java:36)
            at com.vijay.jsonwizard.interactors.JsonFormInteractor.fetchFormElements(JsonFormInteractor.java:56)
            at com.vijay.jsonwizard.presenters.JsonFormFragmentPresenter.addFormElements(JsonFormFragmentPresenter.java:50)
            at com.vijay.jsonwizard.fragments.JsonFormFragment.onViewCreated(JsonFormFragment.java:70)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.popFromBackStack(BackStackRecord.java:960)
            at android.support.v4.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1553)
            at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:506)
            at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:178)
            at com.vijay.jsonwizard.fragments.JsonFormFragment.backClick(JsonFormFragment.java:221)
            at com.vijay.jsonwizard.presenters.JsonFormFragmentPresenter.onBackClick(JsonFormFragmentPresenter.java:70)
            at com.vijay.jsonwizard.fragments.JsonFormFragment.onOptionsItemSelected(JsonFormFragment.java:95)
            at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:1897)
            at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2046)
            at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:359)
            at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:144)
            at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:99)
            at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:99)
            at android.support.v7.internal.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:190)
            at android.view.View.performClick(View.java:4475)
            at android.view.View$PerformClick.run(View.java:18786)
            at android.os.Handler.handleCallback(Handler.java:730)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:176)
            at android.app.ActivityThread.main(ActivityThread.java:5419)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by vijayrawatsan** [comment]
I pushed some changes to load large bitmaps efficiently in https://github.com/vijayrawatsan/android-json-form-wizard/commit/a1cfe32658be765c664f856bc60340c1d1bc55dd 
Please fetch latest code and run. Let me know if you are still getting OOM

**Comment by niteshkhilwani** [comment]
Superb mate. 
Worked like a charm!!

Thanks. :+1:
