### ISSUE TITLE
ClassCastException when trying to fill EditText

### ISSUE THREAD

**Issue by kedjeha** [vijayrawatsan/android-json-form-wizard#16]
Hi,

When i try to fill an EditText, the application crashes with the error below . I'm using appcompat-v7:22.2.1 

java.lang.ClassCastException: android.support.v7.internal.widget.TintContextWrapper cannot be cast to com.vijay.jsonwizard.interfaces.JsonApi
            at com.vijay.jsonwizard.customviews.GenericTextWatcher.afterTextChanged(GenericTextWatcher.java:30)
            at android.widget.TextView.sendAfterTextChanged(TextView.java:7722)
            at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:9493)
            at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:972)
            at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:516)
            at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:454)
            at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:33)
            at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:685)
            at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:445)
            at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:340)
            at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:211)
            at android.app.ActivityThread.main(ActivityThread.java:5321)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Comment by vijayrawatsan** [comment]
@kedjeha I think you are using an older version of the library. Please pull the latest code and try. This issue has been fixed.
