### ISSUE TITLE
Landscape

### ISSUE THREAD

**Issue by NilakArgento** [vijayrawatsan/android-json-form-wizard#18]
Error on change from portrait to landscape

```
FATAL EXCEPTION: main
    Process: us.ethnicmedia.sevendays, PID: 4560
    java.lang.RuntimeException: Unable to start activity ComponentInfo{us.ethnicmedia.sevendays/com.vijay.jsonwizard.activities.JsonFormActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.vijay.jsonwizard.mvp.ViewState.setSavedInstance(boolean)' on a null object reference
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3947)
            at android.app.ActivityThread.access$900(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.vijay.jsonwizard.mvp.ViewState.setSavedInstance(boolean)' on a null object reference
            at com.vijay.jsonwizard.mvp.BaseFragment.onCreate(BaseFragment.java:26)
            at com.vijay.jsonwizard.fragments.JsonFormFragment.onCreate(JsonFormFragment.java:58)
            at android.support.v4.app.Fragment.performCreate(Fragment.java:1766)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:917)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1120)
            at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:1924)
            at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:268)
            at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:58)
            at com.vijay.jsonwizard.activities.JsonFormActivity.onCreate(JsonFormActivity.java:36)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3947)
            at android.app.ActivityThread.access$900(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by vijayrawatsan** [comment]
@NilakArgento I did't intended this library for landscape use. Also didn't test it in landscape mode. Does orientation changes work properly in demo?
