### ISSUE TITLE
all android error inflate

### ISSUE THREAD

**Issue by croccio** [vijayrawatsan/android-json-form-wizard#28]
activity and fragment are blank. i'm running sample app

here logcat

`03-10 16:31:17.822 21312-21312/com.paybay.quismartm E/Minikin: addFontFromAsset failed to create font font/Roboto-Regular.ttf
03-10 16:31:17.822 21312-21312/com.paybay.quismartm D/JsonFormInteractor: Exception occurred in making child view at index : 0 : Exception is : Binary XML file line #1: Binary XML file line #1: Error inflating class <unknown>
03-10 16:31:17.822 21312-21312/com.paybay.quismartm W/System.err: android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class <unknown>
03-10 16:31:17.823 21312-21312/com.paybay.quismartm W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
03-10 16:31:17.823 21312-21312/com.paybay.quismartm W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
03-10 16:31:17.823 21312-21312/com.paybay.quismartm W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
03-10 16:31:17.823 21312-21312/com.paybay.quismartm W/System.err:     at com.vijay.jsonwizard.interactors.JsonFormInteractor.getViewsFromJson(JsonFormInteractor.java:142)
03-10 16:31:17.823 21312-21312/com.paybay.quismartm W/System.err:     at com.vijay.jsonwizard.interactors.JsonFormInteractor.fetchFormElements(JsonFormInteractor.java:56)
03-10 16:31:17.823 21312-21312/com.paybay.quismartm W/System.err:     at com.vijay.jsonwizard.presenters.JsonFormFragmentPresenter.addFormElements(JsonFormFragmentPresenter.java:49)
03-10 16:31:17.823 21312-21312/com.paybay.quismartm W/System.err:     at com.vijay.jsonwizard.fragments.JsonFormFragment.onViewCreated(JsonFormFragment.java:69)
03-10 16:31:17.823 21312-21312/com.paybay.quismartm W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086)
03-10 16:31:17.823 21312-21312/com.paybay.quismartm W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
03-10 16:31:17.823 21312-21312/com.paybay.quismartm W/System.err:     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
03-10 16:31:17.823 21312-21312/com.paybay.quismartm W/System.err:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
03-10 16:31:17.823 21312-21312/com.paybay.quismartm W/System.err:     at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
03-10 16:31:17.823 21312-21312/com.paybay.quismartm W/System.err:     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
03-10 16:31:17.823 21312-21312/com.paybay.quismartm W/System.err:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
03-10 16:31:17.823 21312-21312/com.paybay.quismartm W/System.err:     at android.app.Activity.performStart(Activity.java:6268)
03-10 16:31:17.823 21312-21312/com.paybay.quismartm W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
03-10 16:31:17.823 21312-21312/com.paybay.quismartm W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
03-10 16:31:17.823 21312-21312/com.paybay.quismartm W/System.err:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
03-10 16:31:17.823 21312-21312/com.paybay.quismartm W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
03-10 16:31:17.823 21312-21312/com.paybay.quismartm W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-10 16:31:17.823 21312-21312/com.paybay.quismartm W/System.err:     at android.os.Looper.loop(Looper.java:148)
03-10 16:31:17.823 21312-21312/com.paybay.quismartm W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
03-10 16:31:17.823 21312-21312/com.paybay.quismartm W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-10 16:31:17.824 21312-21312/com.paybay.quismartm W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-10 16:31:17.824 21312-21312/com.paybay.quismartm W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-10 16:31:17.824 21312-21312/com.paybay.quismartm W/System.err: Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class <unknown>
03-10 16:31:17.824 21312-21312/com.paybay.quismartm W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:645)
03-10 16:31:17.824 21312-21312/com.paybay.quismartm W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
03-10 16:31:17.824 21312-21312/com.paybay.quismartm W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
03-10 16:31:17.824 21312-21312/com.paybay.quismartm W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
03-10 16:31:17.824 21312-21312/com.paybay.quismartm W/System.err:   ... 24 more
03-10 16:31:17.824 21312-21312/com.paybay.quismartm W/System.err: Caused by: java.lang.reflect.InvocationTargetException
03-10 16:31:17.824 21312-21312/com.paybay.quismartm W/System.err:     at java.lang.reflect.Constructor.newInstance(Native Method)
03-10 16:31:17.824 21312-21312/com.paybay.quismartm W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:619)
03-10 16:31:17.824 21312-21312/com.paybay.quismartm W/System.err:   ... 27 more
03-10 16:31:17.824 21312-21312/com.paybay.quismartm W/System.err: Caused by: java.lang.RuntimeException: Font asset not found font/Roboto-Regular.ttf
03-10 16:31:17.824 21312-21312/com.paybay.quismartm W/System.err:     at android.graphics.Typeface.createFromAsset(Typeface.java:190)
03-10 16:31:17.825 21312-21312/com.paybay.quismartm W/System.err:     at com.rengwuxian.materialedittext.MaterialEditText.getCustomTypeface(MaterialEditText.java:478)
03-10 16:31:17.825 21312-21312/com.paybay.quismartm W/System.err:     at com.rengwuxian.materialedittext.MaterialEditText.init(MaterialEditText.java:381)
03-10 16:31:17.825 21312-21312/com.paybay.quismartm W/System.err:     at com.rengwuxian.materialedittext.MaterialEditText.<init>(MaterialEditText.java:316)
03-10 16:31:17.825 21312-21312/com.paybay.quismartm W/System.err:   ... 29 more
03-10 16:31:17.826 21312-21312/com.paybay.quismartm E/Minikin: addFontFromAsset failed to create font font/Roboto-Regular.ttf
03-10 16:31:17.826 21312-21312/com.paybay.quismartm D/JsonFormInteractor: Exception occurred in making child view at index : 1 : Exception is : Binary XML file line #1: Binary XML file line #1: Error inflating class <unknown>
03-10 16:31:17.826 21312-21312/com.paybay.quismartm W/System.err: android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class <unknown>
03-10 16:31:17.826 21312-21312/com.paybay.quismartm W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
03-10 16:31:17.826 21312-21312/com.paybay.quismartm W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
03-10 16:31:17.826 21312-21312/com.paybay.quismartm W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
03-10 16:31:17.826 21312-21312/com.paybay.quismartm W/System.err:     at com.vijay.jsonwizard.interactors.JsonFormInteractor.getViewsFromJson(JsonFormInteractor.java:142)
03-10 16:31:17.826 21312-21312/com.paybay.quismartm W/System.err:     at com.vijay.jsonwizard.interactors.JsonFormInteractor.fetchFormElements(JsonFormInteractor.java:56)
03-10 16:31:17.826 21312-21312/com.paybay.quismartm W/System.err:     at com.vijay.jsonwizard.presenters.JsonFormFragmentPresenter.addFormElements(JsonFormFragmentPresenter.java:49)
03-10 16:31:17.827 21312-21312/com.paybay.quismartm W/System.err:     at com.vijay.jsonwizard.fragments.JsonFormFragment.onViewCreated(JsonFormFragment.java:69)
03-10 16:31:17.827 21312-21312/com.paybay.quismartm W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086)
03-10 16:31:17.827 21312-21312/com.paybay.quismartm W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
03-10 16:31:17.827 21312-21312/com.paybay.quismartm W/System.err:     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
03-10 16:31:17.827 21312-21312/com.paybay.quismartm W/System.err:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
03-10 16:31:17.827 21312-21312/com.paybay.quismartm W/System.err:     at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
03-10 16:31:17.827 21312-21312/com.paybay.quismartm W/System.err:     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
03-10 16:31:17.827 21312-21312/com.paybay.quismartm W/System.err:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
03-10 16:31:17.827 21312-21312/com.paybay.quismartm W/System.err:     at android.app.Activity.performStart(Activity.java:6268)
03-10 16:31:17.827 21312-21312/com.paybay.quismartm W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
03-10 16:31:17.827 21312-21312/com.paybay.quismartm W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
03-10 16:31:17.827 21312-21312/com.paybay.quismartm W/System.err:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
03-10 16:31:17.827 21312-21312/com.paybay.quismartm W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
03-10 16:31:17.827 21312-21312/com.paybay.quismartm W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-10 16:31:17.827 21312-21312/com.paybay.quismartm W/System.err:     at android.os.Looper.loop(Looper.java:148)
03-10 16:31:17.827 21312-21312/com.paybay.quismartm W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
03-10 16:31:17.827 21312-21312/com.paybay.quismartm W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-10 16:31:17.827 21312-21312/com.paybay.quismartm W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-10 16:31:17.827 21312-21312/com.paybay.quismartm W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-10 16:31:17.827 21312-21312/com.paybay.quismartm W/System.err: Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class <unknown>
03-10 16:31:17.827 21312-21312/com.paybay.quismartm W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:645)
03-10 16:31:17.827 21312-21312/com.paybay.quismartm W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
03-10 16:31:17.828 21312-21312/com.paybay.quismartm W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
03-10 16:31:17.828 21312-21312/com.paybay.quismartm W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
03-10 16:31:17.828 21312-21312/com.paybay.quismartm W/System.err:   ... 24 more
03-10 16:31:17.828 21312-21312/com.paybay.quismartm W/System.err: Caused by: java.lang.reflect.InvocationTargetException
03-10 16:31:17.828 21312-21312/com.paybay.quismartm W/System.err:     at java.lang.reflect.Constructor.newInstance(Native Method)
03-10 16:31:17.828 21312-21312/com.paybay.quismartm W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:619)
03-10 16:31:17.828 21312-21312/com.paybay.quismartm W/System.err:   ... 27 more
03-10 16:31:17.828 21312-21312/com.paybay.quismartm W/System.err: Caused by: java.lang.RuntimeException: Font asset not found font/Roboto-Regular.ttf
03-10 16:31:17.828 21312-21312/com.paybay.quismartm W/System.err:     at android.graphics.Typeface.createFromAsset(Typeface.java:190)
03-10 16:31:17.828 21312-21312/com.paybay.quismartm W/System.err:     at com.rengwuxian.materialedittext.MaterialEditText.getCustomTypeface(MaterialEditText.java:478)
03-10 16:31:17.828 21312-21312/com.paybay.quismartm W/System.err:     at com.rengwuxian.materialedittext.MaterialEditText.init(MaterialEditText.java:381)
03-10 16:31:17.828 21312-21312/com.paybay.quismartm W/System.err:     at com.rengwuxian.materialedittext.MaterialEditText.<init>(MaterialEditText.java:316)
03-10 16:31:17.828 21312-21312/com.paybay.quismartm W/System.err:   ... 29 more
03-10 16:31:17.829 21312-21312/com.paybay.quismartm E/Minikin: addFontFromAsset failed to create font font/Roboto-Bold.ttf
03-10 16:31:17.829 21312-21312/com.paybay.quismartm D/JsonFormInteractor: Exception occurred in making child view at index : 2 : Exception is : Font asset not found font/Roboto-Bold.ttf
03-10 16:31:17.829 21312-21312/com.paybay.quismartm W/System.err: java.lang.RuntimeException: Font asset not found font/Roboto-Bold.ttf
03-10 16:31:17.829 21312-21312/com.paybay.quismartm W/System.err:     at android.graphics.Typeface.createFromAsset(Typeface.java:190)
03-10 16:31:17.829 21312-21312/com.paybay.quismartm W/System.err:     at com.vijay.jsonwizard.interactors.JsonFormInteractor.getTextViewWith(JsonFormInteractor.java:202)
03-10 16:31:17.829 21312-21312/com.paybay.quismartm W/System.err:     at com.vijay.jsonwizard.interactors.JsonFormInteractor.getViewsFromJson(JsonFormInteractor.java:81)
03-10 16:31:17.830 21312-21312/com.paybay.quismartm W/System.err:     at com.vijay.jsonwizard.interactors.JsonFormInteractor.fetchFormElements(JsonFormInteractor.java:56)
03-10 16:31:17.830 21312-21312/com.paybay.quismartm W/System.err:     at com.vijay.jsonwizard.presenters.JsonFormFragmentPresenter.addFormElements(JsonFormFragmentPresenter.java:49)
03-10 16:31:17.830 21312-21312/com.paybay.quismartm W/System.err:     at com.vijay.jsonwizard.fragments.JsonFormFragment.onViewCreated(JsonFormFragment.java:69)
03-10 16:31:17.830 21312-21312/com.paybay.quismartm W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086)
03-10 16:31:17.830 21312-21312/com.paybay.quismartm W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
03-10 16:31:17.830 21312-21312/com.paybay.quismartm W/System.err:     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
03-10 16:31:17.830 21312-21312/com.paybay.quismartm W/System.err:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
03-10 16:31:17.830 21312-21312/com.paybay.quismartm W/System.err:     at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
03-10 16:31:17.830 21312-21312/com.paybay.quismartm W/System.err:     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
03-10 16:31:17.830 21312-21312/com.paybay.quismartm W/System.err:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
03-10 16:31:17.830 21312-21312/com.paybay.quismartm W/System.err:     at android.app.Activity.performStart(Activity.java:6268)
03-10 16:31:17.830 21312-21312/com.paybay.quismartm W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
03-10 16:31:17.830 21312-21312/com.paybay.quismartm W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
03-10 16:31:17.830 21312-21312/com.paybay.quismartm W/System.err:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
03-10 16:31:17.830 21312-21312/com.paybay.quismartm W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
03-10 16:31:17.830 21312-21312/com.paybay.quismartm W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-10 16:31:17.830 21312-21312/com.paybay.quismartm W/System.err:     at android.os.Looper.loop(Looper.java:148)
03-10 16:31:17.830 21312-21312/com.paybay.quismartm W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
03-10 16:31:17.830 21312-21312/com.paybay.quismartm W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-10 16:31:17.830 21312-21312/com.paybay.quismartm W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-10 16:31:17.830 21312-21312/com.paybay.quismartm W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-10 16:31:17.996 21312-21326/com.paybay.quismartm D/OpenGLRenderer: endAllStagingAnimators on 0x7f63e73c00 (RippleDrawable) with handle 0x7f6740f740`

**Comment by abruzzi** [comment]
Looks I got seam issues here, any updates?

**Comment by chobela** [comment]
Hi did you solve this issue?
