### ISSUE TITLE
java.lang.ClassNotFoundException on EditText text change event.

### ISSUE THREAD

**Issue by adityagundecha** [vijayrawatsan/android-json-form-wizard#29]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: konzeptfabrica.com.vehicloadmin, PID: 27961
                                                                                 java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/internal/widget/TintContextWrapper;
                                                                                     at com.vijay.jsonwizard.customviews.GenericTextWatcher.afterTextChanged(GenericTextWatcher.java:35)
                                                                                     at android.widget.TextView.sendAfterTextChanged(TextView.java:7698)
                                                                                     at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:9486)
                                                                                     at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:972)
                                                                                     at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:516)
                                                                                     at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:454)
                                                                                     at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:33)
                                                                                     at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:685)
                                                                                     at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:445)
                                                                                     at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:340)
                                                                                     at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5300)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
                                                                                     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
                                                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.internal.widget.TintContextWrapper" on path: DexPathList[[zip file "/data/app/konzeptfabrica.com.vehicloadmin-2/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
                                                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                     at com.vijay.jsonwizard.customviews.GenericTextWatcher.afterTextChanged(GenericTextWatcher.java:35) 
                                                                                     at android.widget.TextView.sendAfterTextChanged(TextView.java:7698) 
                                                                                     at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:9486) 
                                                                                     at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:972) 
                                                                                     at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:516) 
                                                                                     at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:454) 
                                                                                     at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:33) 
                                                                                     at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:685) 
                                                                                     at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:445) 
                                                                                     at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:340) 
                                                                                     at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                     at android.os.Looper.loop(Looper.java:135) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5300) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 
                                                                                     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114) 
                                                                                    Suppressed: java.lang.ClassNotFoundException: android.support.v7.internal.widget.TintContextWrapper
                                                                                     at java.lang.Class.classForName(Native Method)
                                                                                     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                            ... 20 more
                                                                                  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by adityagundecha** [comment]
I think the culprit is "com.rengwuxian.materialedittext"
Please take a look.

**Comment by adityagundecha** [comment]
changed TintContextWrapper to ContextWrapper
this solved the issue.
