### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by ryanhaidy** [vijayrawatsan/android-json-form-wizard#42]
I got an error in my sample project using this library that says:

FATAL EXCEPTION: main
                  Process: com.garudainfinity.leumartsurvey, PID: 30819
                  java.lang.NoClassDefFoundError: com.vijay.jsonwizard.activities.JsonFormActivity
                      at com.garudainfinity.leumartsurvey.activities.SurveyListActivity.onClick(SurveyListActivity.java:156)
                      at android.view.View.performClick(View.java:5214)
                      at android.view.View$PerformClick.run(View.java:20978)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:145)
                      at android.app.ActivityThread.main(ActivityThread.java:6134)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

this is how i call the activity:
  intent = new Intent(this, JsonFormActivity.class);
  String json = "Your complete JSON";
  intent.putExtra("json", json);
  startActivityForResult(intent, 1);

am i doing this wrong?

**Comment by moanes1** [comment]
the same happened to me

**Comment by vijaysakthi** [comment]
> I got an error in my sample project using this library that says:
> 
> FATAL EXCEPTION: main
> Process: com.garudainfinity.leumartsurvey, PID: 30819
> java.lang.NoClassDefFoundError: com.vijay.jsonwizard.activities.JsonFormActivity
> at com.garudainfinity.leumartsurvey.activities.SurveyListActivity.onClick(SurveyListActivity.java:156)
> at android.view.View.performClick(View.java:5214)
> at android.view.View$PerformClick.run(View.java:20978)
> at android.os.Handler.handleCallback(Handler.java:739)
> at android.os.Handler.dispatchMessage(Handler.java:95)
> at android.os.Looper.loop(Looper.java:145)
> at android.app.ActivityThread.main(ActivityThread.java:6134)
> at java.lang.reflect.Method.invoke(Native Method)
> at java.lang.reflect.Method.invoke(Method.java:372)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
> 
> this is how i call the activity:
> intent = new Intent(this, JsonFormActivity.class);
> String json = "Your complete JSON";
> intent.putExtra("json", json);
> startActivityForResult(intent, 1);
> 
> am i doing this wrong?

Did u find the solution for this error?? Could u help me solving this issue?? @ryanhaidy

**Comment by vijaysakthi** [comment]
@vijayrawatsan  Could you help me solve this issue ?? ...
java.lang.NoClassDefFoundError: com.vijay.jsonwizard.activities.JsonFormActivity
